### ISSUE TITLE
FAculty page issues

### ISSUE THREAD

**Issue by atulitha** [UCEV-CSE-Portal/department-portal#2]
broken img src and directory paths are case sensitive
![image](https://user-images.githubusercontent.com/9493166/109923959-912e0780-7ce5-11eb-93eb-b7361ebed319.png)
this is in the faculty.php
![image](https://user-images.githubusercontent.com/9493166/109924173-e5d18280-7ce5-11eb-86ee-d9a18e543daf.png)
but this is supposed to be there with case sensitive 
![image](https://user-images.githubusercontent.com/9493166/109924345-25986a00-7ce6-11eb-93c0-0d8dca949452.png)

**Comment by josephkishoresfdev** [comment]
changed all names
