### ISSUE TITLE
faculty.php issues

### ISSUE THREAD

**Issue by atulitha** [UCEV-CSE-Portal/department-portal#3]
![image](https://user-images.githubusercontent.com/9493166/109924682-aa838380-7ce6-11eb-98e6-2beeea720069.png)
no file or directory named boxicons
![image](https://user-images.githubusercontent.com/9493166/109924799-d9015e80-7ce6-11eb-8d35-9be783f733e9.png)

**Comment by josephkishoresfdev** [comment]
removed that line - improper linking
