### ISSUE TITLE
student achievements

### ISSUE THREAD

**Issue by atulitha** [UCEV-CSE-Portal/department-portal#5]
![image](https://user-images.githubusercontent.com/9493166/109925409-b7ed3d80-7ce7-11eb-80e3-b66b04d7a9e9.png)

no file or directory

![image](https://user-images.githubusercontent.com/9493166/109925456-ca677700-7ce7-11eb-9d48-d7b71f8eea98.png)

**Comment by josephkishoresfdev** [comment]
file not exists and not needed

**Comment by josephkishoresfdev** [comment]
hence removed the line
